### PR TITLE
Added link to 1.0 and updated other links to https

### PR DESCRIPTION
**Pull request by metasim**
Update for https://github.com/locationtech/geotrellis/issues/2377

### CODE REVIEW

**Comment by metasim** [comment]
Build is failing because of this:

    sbt.ResolveException: download failed: javax.media#jai_core;1.1.3!jai_core.jar

which I don't think has anything to do with this PR.

**Comment by metasim** [comment]
(Partially addresses #54)

**Comment by metasim** [comment]
@lossyrob 
Build is failing because of this:

    sbt.ResolveException: download failed: javax.media#jai_core;1.1.3!jai_core.jar

which I don't think has anything to do with this PR.

**Comment by hectcastro** [comment]
I triggered the build again and it succeeded. I opened https://github.com/geotrellis/geotrellis-site/issues/79 to address the issue, but should unblock this PR.

**Comment by fosskers** [comment]
Confirming locally, then I'll merge.

**Pull request merged**
