### PR TITLE
Vagrant -> Docker

### PR DESCRIPTION
**Pull request by fosskers**
### TODO
- [x] Static site container (jekyll + nginx)
- [x] Dynamic Geotrellis container (left as `0.9`)
- [x] `docker-compose` behaviour
- [x] Update `Documentation` page
- [x] Fix hillshade issues

### Motivation
A deployment backed by docker should be easier to use/contribute to for everyone.

Connects azavea/geotrellis#10 .

### CODE REVIEW

**Comment by fosskers** [comment]
Connect azavea/geotrellis#10

**Comment by fosskers** [comment]
```console
colin@yumi ~> echo "GET http://localhost:8080" | vegeta -cpus=4 attack -duration=10s | tee results.bin | vegeta report
Requests      [total, rate]            500, 50.10
Duration      [total, attack, wait]    9.980678377s, 9.979999921s, 678.456µs
Latencies     [mean, 50, 95, 99, max]  763.51µs, 756.221µs, 874.482µs, 1.135452ms, 1.390831ms
Bytes In      [total, mean]            8542000, 17084.00
Bytes Out     [total, mean]            0, 0.00
Success       [ratio]                  100.00%
Status Codes  [code:count]             200:500  
Error Set:
```

**Comment by lossyrob** [comment]
@fosskers looks like there's a directory named specifically for your comp somewhere..when I do `docker-compose up`, I get

```console
Creating geotrellissite_jekyll_1

ERROR: for geotrellis  Cannot start service geotrellis: Mounts denied: sxfs/#namespaces for more info.
.
 and /home/colin/.m2 and /home/colin/.sbt
are not shared from OS X and are not known to Docker.
```
(after a while)

**Comment by fosskers** [comment]
My oversight, yeah. I'll retest with `~`.

**Pull request merged**
